// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/coordinator/coordinator.proto

package cdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	cmpb "lab_3/proto/common/cmpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_coordinator_coordinator_proto protoreflect.FileDescriptor

const file_proto_coordinator_coordinator_proto_rawDesc = "" +
	"\n" +
	"#proto/coordinator/coordinator.proto\x12\vcoordinator\x1a\x19proto/common/common.proto2\xd7\x01\n" +
	"\x12CoordinatorService\x127\n" +
	"\bGetSeats\x12\x14.common.SeatsRequest\x1a\x15.common.SeatsResponse\x12:\n" +
	"\aCheckIn\x12\x16.common.CheckInRequest\x1a\x17.common.CheckInResponse\x12L\n" +
	"\x0fGetBoardingPass\x12\x1b.common.BoardingPassRequest\x1a\x1c.common.BoardingPassResponseB#Z!lab_3/proto/coordinator/cdpb;cdpbb\x06proto3"

var file_proto_coordinator_coordinator_proto_goTypes = []any{
	(*cmpb.SeatsRequest)(nil),         // 0: common.SeatsRequest
	(*cmpb.CheckInRequest)(nil),       // 1: common.CheckInRequest
	(*cmpb.BoardingPassRequest)(nil),  // 2: common.BoardingPassRequest
	(*cmpb.SeatsResponse)(nil),        // 3: common.SeatsResponse
	(*cmpb.CheckInResponse)(nil),      // 4: common.CheckInResponse
	(*cmpb.BoardingPassResponse)(nil), // 5: common.BoardingPassResponse
}
var file_proto_coordinator_coordinator_proto_depIdxs = []int32{
	0, // 0: coordinator.CoordinatorService.GetSeats:input_type -> common.SeatsRequest
	1, // 1: coordinator.CoordinatorService.CheckIn:input_type -> common.CheckInRequest
	2, // 2: coordinator.CoordinatorService.GetBoardingPass:input_type -> common.BoardingPassRequest
	3, // 3: coordinator.CoordinatorService.GetSeats:output_type -> common.SeatsResponse
	4, // 4: coordinator.CoordinatorService.CheckIn:output_type -> common.CheckInResponse
	5, // 5: coordinator.CoordinatorService.GetBoardingPass:output_type -> common.BoardingPassResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_coordinator_coordinator_proto_init() }
func file_proto_coordinator_coordinator_proto_init() {
	if File_proto_coordinator_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coordinator_coordinator_proto_rawDesc), len(file_proto_coordinator_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coordinator_coordinator_proto_goTypes,
		DependencyIndexes: file_proto_coordinator_coordinator_proto_depIdxs,
	}.Build()
	File_proto_coordinator_coordinator_proto = out.File
	file_proto_coordinator_coordinator_proto_goTypes = nil
	file_proto_coordinator_coordinator_proto_depIdxs = nil
}
