// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/datanode/datanode.proto

package dpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	cmpb "lab_3/proto/common/cmpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatanodeService_ApplyUpdate_FullMethodName     = "/datanode.DatanodeService/ApplyUpdate"
	DatanodeService_Gossip_FullMethodName          = "/datanode.DatanodeService/Gossip"
	DatanodeService_GetSeats_FullMethodName        = "/datanode.DatanodeService/GetSeats"
	DatanodeService_GetFlightState_FullMethodName  = "/datanode.DatanodeService/GetFlightState"
	DatanodeService_GetBoardingPass_FullMethodName = "/datanode.DatanodeService/GetBoardingPass"
	DatanodeService_CheckIn_FullMethodName         = "/datanode.DatanodeService/CheckIn"
)

// DatanodeServiceClient is the client API for DatanodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatanodeServiceClient interface {
	ApplyUpdate(ctx context.Context, in *cmpb.FlightUpdate, opts ...grpc.CallOption) (*cmpb.Empty, error)
	Gossip(ctx context.Context, in *cmpb.FlightUpdate, opts ...grpc.CallOption) (*cmpb.Empty, error)
	GetSeats(ctx context.Context, in *cmpb.SeatsRequest, opts ...grpc.CallOption) (*cmpb.SeatsResponse, error)
	GetFlightState(ctx context.Context, in *cmpb.GetFlightRequest, opts ...grpc.CallOption) (*cmpb.FlightState, error)
	GetBoardingPass(ctx context.Context, in *cmpb.BoardingPassRequest, opts ...grpc.CallOption) (*cmpb.BoardingPassResponse, error)
	CheckIn(ctx context.Context, in *cmpb.CheckInRequest, opts ...grpc.CallOption) (*cmpb.CheckInResponse, error)
}

type datanodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatanodeServiceClient(cc grpc.ClientConnInterface) DatanodeServiceClient {
	return &datanodeServiceClient{cc}
}

func (c *datanodeServiceClient) ApplyUpdate(ctx context.Context, in *cmpb.FlightUpdate, opts ...grpc.CallOption) (*cmpb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cmpb.Empty)
	err := c.cc.Invoke(ctx, DatanodeService_ApplyUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) Gossip(ctx context.Context, in *cmpb.FlightUpdate, opts ...grpc.CallOption) (*cmpb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cmpb.Empty)
	err := c.cc.Invoke(ctx, DatanodeService_Gossip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) GetSeats(ctx context.Context, in *cmpb.SeatsRequest, opts ...grpc.CallOption) (*cmpb.SeatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cmpb.SeatsResponse)
	err := c.cc.Invoke(ctx, DatanodeService_GetSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) GetFlightState(ctx context.Context, in *cmpb.GetFlightRequest, opts ...grpc.CallOption) (*cmpb.FlightState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cmpb.FlightState)
	err := c.cc.Invoke(ctx, DatanodeService_GetFlightState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) GetBoardingPass(ctx context.Context, in *cmpb.BoardingPassRequest, opts ...grpc.CallOption) (*cmpb.BoardingPassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cmpb.BoardingPassResponse)
	err := c.cc.Invoke(ctx, DatanodeService_GetBoardingPass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) CheckIn(ctx context.Context, in *cmpb.CheckInRequest, opts ...grpc.CallOption) (*cmpb.CheckInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cmpb.CheckInResponse)
	err := c.cc.Invoke(ctx, DatanodeService_CheckIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatanodeServiceServer is the server API for DatanodeService service.
// All implementations must embed UnimplementedDatanodeServiceServer
// for forward compatibility.
type DatanodeServiceServer interface {
	ApplyUpdate(context.Context, *cmpb.FlightUpdate) (*cmpb.Empty, error)
	Gossip(context.Context, *cmpb.FlightUpdate) (*cmpb.Empty, error)
	GetSeats(context.Context, *cmpb.SeatsRequest) (*cmpb.SeatsResponse, error)
	GetFlightState(context.Context, *cmpb.GetFlightRequest) (*cmpb.FlightState, error)
	GetBoardingPass(context.Context, *cmpb.BoardingPassRequest) (*cmpb.BoardingPassResponse, error)
	CheckIn(context.Context, *cmpb.CheckInRequest) (*cmpb.CheckInResponse, error)
	mustEmbedUnimplementedDatanodeServiceServer()
}

// UnimplementedDatanodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatanodeServiceServer struct{}

func (UnimplementedDatanodeServiceServer) ApplyUpdate(context.Context, *cmpb.FlightUpdate) (*cmpb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyUpdate not implemented")
}
func (UnimplementedDatanodeServiceServer) Gossip(context.Context, *cmpb.FlightUpdate) (*cmpb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Gossip not implemented")
}
func (UnimplementedDatanodeServiceServer) GetSeats(context.Context, *cmpb.SeatsRequest) (*cmpb.SeatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeats not implemented")
}
func (UnimplementedDatanodeServiceServer) GetFlightState(context.Context, *cmpb.GetFlightRequest) (*cmpb.FlightState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlightState not implemented")
}
func (UnimplementedDatanodeServiceServer) GetBoardingPass(context.Context, *cmpb.BoardingPassRequest) (*cmpb.BoardingPassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBoardingPass not implemented")
}
func (UnimplementedDatanodeServiceServer) CheckIn(context.Context, *cmpb.CheckInRequest) (*cmpb.CheckInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIn not implemented")
}
func (UnimplementedDatanodeServiceServer) mustEmbedUnimplementedDatanodeServiceServer() {}
func (UnimplementedDatanodeServiceServer) testEmbeddedByValue()                         {}

// UnsafeDatanodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatanodeServiceServer will
// result in compilation errors.
type UnsafeDatanodeServiceServer interface {
	mustEmbedUnimplementedDatanodeServiceServer()
}

func RegisterDatanodeServiceServer(s grpc.ServiceRegistrar, srv DatanodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedDatanodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatanodeService_ServiceDesc, srv)
}

func _DatanodeService_ApplyUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cmpb.FlightUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).ApplyUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_ApplyUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).ApplyUpdate(ctx, req.(*cmpb.FlightUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_Gossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cmpb.FlightUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).Gossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_Gossip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).Gossip(ctx, req.(*cmpb.FlightUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_GetSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cmpb.SeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).GetSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_GetSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).GetSeats(ctx, req.(*cmpb.SeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_GetFlightState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cmpb.GetFlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).GetFlightState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_GetFlightState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).GetFlightState(ctx, req.(*cmpb.GetFlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_GetBoardingPass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cmpb.BoardingPassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).GetBoardingPass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_GetBoardingPass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).GetBoardingPass(ctx, req.(*cmpb.BoardingPassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cmpb.CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_CheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).CheckIn(ctx, req.(*cmpb.CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatanodeService_ServiceDesc is the grpc.ServiceDesc for DatanodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatanodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datanode.DatanodeService",
	HandlerType: (*DatanodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyUpdate",
			Handler:    _DatanodeService_ApplyUpdate_Handler,
		},
		{
			MethodName: "Gossip",
			Handler:    _DatanodeService_Gossip_Handler,
		},
		{
			MethodName: "GetSeats",
			Handler:    _DatanodeService_GetSeats_Handler,
		},
		{
			MethodName: "GetFlightState",
			Handler:    _DatanodeService_GetFlightState_Handler,
		},
		{
			MethodName: "GetBoardingPass",
			Handler:    _DatanodeService_GetBoardingPass_Handler,
		},
		{
			MethodName: "CheckIn",
			Handler:    _DatanodeService_CheckIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/datanode/datanode.proto",
}
