// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/datanode/datanode.proto

package dpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	cmpb "lab_3/proto/common/cmpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_datanode_datanode_proto protoreflect.FileDescriptor

const file_proto_datanode_datanode_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/datanode/datanode.proto\x12\bdatanode\x1a\x19proto/common/common.proto2\xf8\x02\n" +
	"\x0fDatanodeService\x122\n" +
	"\vApplyUpdate\x12\x14.common.FlightUpdate\x1a\r.common.Empty\x12-\n" +
	"\x06Gossip\x12\x14.common.FlightUpdate\x1a\r.common.Empty\x127\n" +
	"\bGetSeats\x12\x14.common.SeatsRequest\x1a\x15.common.SeatsResponse\x12?\n" +
	"\x0eGetFlightState\x12\x18.common.GetFlightRequest\x1a\x13.common.FlightState\x12L\n" +
	"\x0fGetBoardingPass\x12\x1b.common.BoardingPassRequest\x1a\x1c.common.BoardingPassResponse\x12:\n" +
	"\aCheckIn\x12\x16.common.CheckInRequest\x1a\x17.common.CheckInResponseB\x1eZ\x1clab_3/proto/datanode/dpb;dpbb\x06proto3"

var file_proto_datanode_datanode_proto_goTypes = []any{
	(*cmpb.FlightUpdate)(nil),         // 0: common.FlightUpdate
	(*cmpb.SeatsRequest)(nil),         // 1: common.SeatsRequest
	(*cmpb.GetFlightRequest)(nil),     // 2: common.GetFlightRequest
	(*cmpb.BoardingPassRequest)(nil),  // 3: common.BoardingPassRequest
	(*cmpb.CheckInRequest)(nil),       // 4: common.CheckInRequest
	(*cmpb.Empty)(nil),                // 5: common.Empty
	(*cmpb.SeatsResponse)(nil),        // 6: common.SeatsResponse
	(*cmpb.FlightState)(nil),          // 7: common.FlightState
	(*cmpb.BoardingPassResponse)(nil), // 8: common.BoardingPassResponse
	(*cmpb.CheckInResponse)(nil),      // 9: common.CheckInResponse
}
var file_proto_datanode_datanode_proto_depIdxs = []int32{
	0, // 0: datanode.DatanodeService.ApplyUpdate:input_type -> common.FlightUpdate
	0, // 1: datanode.DatanodeService.Gossip:input_type -> common.FlightUpdate
	1, // 2: datanode.DatanodeService.GetSeats:input_type -> common.SeatsRequest
	2, // 3: datanode.DatanodeService.GetFlightState:input_type -> common.GetFlightRequest
	3, // 4: datanode.DatanodeService.GetBoardingPass:input_type -> common.BoardingPassRequest
	4, // 5: datanode.DatanodeService.CheckIn:input_type -> common.CheckInRequest
	5, // 6: datanode.DatanodeService.ApplyUpdate:output_type -> common.Empty
	5, // 7: datanode.DatanodeService.Gossip:output_type -> common.Empty
	6, // 8: datanode.DatanodeService.GetSeats:output_type -> common.SeatsResponse
	7, // 9: datanode.DatanodeService.GetFlightState:output_type -> common.FlightState
	8, // 10: datanode.DatanodeService.GetBoardingPass:output_type -> common.BoardingPassResponse
	9, // 11: datanode.DatanodeService.CheckIn:output_type -> common.CheckInResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_datanode_datanode_proto_init() }
func file_proto_datanode_datanode_proto_init() {
	if File_proto_datanode_datanode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_datanode_datanode_proto_rawDesc), len(file_proto_datanode_datanode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_datanode_datanode_proto_goTypes,
		DependencyIndexes: file_proto_datanode_datanode_proto_depIdxs,
	}.Build()
	File_proto_datanode_datanode_proto = out.File
	file_proto_datanode_datanode_proto_goTypes = nil
	file_proto_datanode_datanode_proto_depIdxs = nil
}
