// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/consensus/consensus.proto

package cspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunwayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"` //"ASSIGN" o "RELEASE"
	RunwayId      string                 `protobuf:"bytes,3,opt,name=runway_id,json=runwayId,proto3" json:"runway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunwayRequest) Reset() {
	*x = RunwayRequest{}
	mi := &file_proto_consensus_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunwayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunwayRequest) ProtoMessage() {}

func (x *RunwayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunwayRequest.ProtoReflect.Descriptor instead.
func (*RunwayRequest) Descriptor() ([]byte, []int) {
	return file_proto_consensus_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *RunwayRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *RunwayRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *RunwayRequest) GetRunwayId() string {
	if x != nil {
		return x.RunwayId
	}
	return ""
}

type RunwayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RunwayId      string                 `protobuf:"bytes,2,opt,name=runway_id,json=runwayId,proto3" json:"runway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunwayResponse) Reset() {
	*x = RunwayResponse{}
	mi := &file_proto_consensus_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunwayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunwayResponse) ProtoMessage() {}

func (x *RunwayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunwayResponse.ProtoReflect.Descriptor instead.
func (*RunwayResponse) Descriptor() ([]byte, []int) {
	return file_proto_consensus_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *RunwayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RunwayResponse) GetRunwayId() string {
	if x != nil {
		return x.RunwayId
	}
	return ""
}

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`                       // pista
	AssignedTo    string                 `protobuf:"bytes,2,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"` // vuelo
	PrevTerm      int32                  `protobuf:"varint,3,opt,name=prev_term,json=prevTerm,proto3" json:"prev_term,omitempty"`
	PrevIndex     int32                  `protobuf:"varint,4,opt,name=prev_index,json=prevIndex,proto3" json:"prev_index,omitempty"`
	Operation     string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"` //"ASSIGN" o "RELEASE"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_proto_consensus_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_proto_consensus_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *Decision) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Decision) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *Decision) GetPrevTerm() int32 {
	if x != nil {
		return x.PrevTerm
	}
	return 0
}

func (x *Decision) GetPrevIndex() int32 {
	if x != nil {
		return x.PrevIndex
	}
	return 0
}

func (x *Decision) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type DecisionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Committed     bool                   `protobuf:"varint,1,opt,name=committed,proto3" json:"committed,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionAck) Reset() {
	*x = DecisionAck{}
	mi := &file_proto_consensus_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionAck) ProtoMessage() {}

func (x *DecisionAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionAck.ProtoReflect.Descriptor instead.
func (*DecisionAck) Descriptor() ([]byte, []int) {
	return file_proto_consensus_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *DecisionAck) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *DecisionAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_proto_consensus_consensus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_consensus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_consensus_consensus_proto_rawDescGZIP(), []int{4}
}

func (x *VoteRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteGranted   bool                   `protobuf:"varint,1,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_proto_consensus_consensus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_consensus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_consensus_consensus_proto_rawDescGZIP(), []int{5}
}

func (x *VoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

func (x *VoteResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

var File_proto_consensus_consensus_proto protoreflect.FileDescriptor

const file_proto_consensus_consensus_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/consensus/consensus.proto\x12\tconsensus\"g\n" +
	"\rRunwayRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x1b\n" +
	"\trunway_id\x18\x03 \x01(\tR\brunwayId\"G\n" +
	"\x0eRunwayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\trunway_id\x18\x02 \x01(\tR\brunwayId\"\xa1\x01\n" +
	"\bDecision\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x1f\n" +
	"\vassigned_to\x18\x02 \x01(\tR\n" +
	"assignedTo\x12\x1b\n" +
	"\tprev_term\x18\x03 \x01(\x05R\bprevTerm\x12\x1d\n" +
	"\n" +
	"prev_index\x18\x04 \x01(\x05R\tprevIndex\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\"=\n" +
	"\vDecisionAck\x12\x1c\n" +
	"\tcommitted\x18\x01 \x01(\bR\tcommitted\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"D\n" +
	"\vVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\"E\n" +
	"\fVoteResponse\x12!\n" +
	"\fvote_granted\x18\x01 \x01(\bR\vvoteGranted\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term2b\n" +
	"\x10ConsensusService\x12N\n" +
	"\x17RequestRunwayAssignment\x12\x18.consensus.RunwayRequest\x1a\x19.consensus.RunwayResponse2\x96\x01\n" +
	"\x18InternalConsensusService\x12:\n" +
	"\vAppendEntry\x12\x13.consensus.Decision\x1a\x16.consensus.DecisionAck\x12>\n" +
	"\vRequestVote\x12\x16.consensus.VoteRequest\x1a\x17.consensus.VoteResponseB!Z\x1flab_3/proto/consensus/cspb;cspbb\x06proto3"

var (
	file_proto_consensus_consensus_proto_rawDescOnce sync.Once
	file_proto_consensus_consensus_proto_rawDescData []byte
)

func file_proto_consensus_consensus_proto_rawDescGZIP() []byte {
	file_proto_consensus_consensus_proto_rawDescOnce.Do(func() {
		file_proto_consensus_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_consensus_consensus_proto_rawDesc), len(file_proto_consensus_consensus_proto_rawDesc)))
	})
	return file_proto_consensus_consensus_proto_rawDescData
}

var file_proto_consensus_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_consensus_consensus_proto_goTypes = []any{
	(*RunwayRequest)(nil),  // 0: consensus.RunwayRequest
	(*RunwayResponse)(nil), // 1: consensus.RunwayResponse
	(*Decision)(nil),       // 2: consensus.Decision
	(*DecisionAck)(nil),    // 3: consensus.DecisionAck
	(*VoteRequest)(nil),    // 4: consensus.VoteRequest
	(*VoteResponse)(nil),   // 5: consensus.VoteResponse
}
var file_proto_consensus_consensus_proto_depIdxs = []int32{
	0, // 0: consensus.ConsensusService.RequestRunwayAssignment:input_type -> consensus.RunwayRequest
	2, // 1: consensus.InternalConsensusService.AppendEntry:input_type -> consensus.Decision
	4, // 2: consensus.InternalConsensusService.RequestVote:input_type -> consensus.VoteRequest
	1, // 3: consensus.ConsensusService.RequestRunwayAssignment:output_type -> consensus.RunwayResponse
	3, // 4: consensus.InternalConsensusService.AppendEntry:output_type -> consensus.DecisionAck
	5, // 5: consensus.InternalConsensusService.RequestVote:output_type -> consensus.VoteResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_consensus_consensus_proto_init() }
func file_proto_consensus_consensus_proto_init() {
	if File_proto_consensus_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_consensus_consensus_proto_rawDesc), len(file_proto_consensus_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_consensus_consensus_proto_goTypes,
		DependencyIndexes: file_proto_consensus_consensus_proto_depIdxs,
		MessageInfos:      file_proto_consensus_consensus_proto_msgTypes,
	}.Build()
	File_proto_consensus_consensus_proto = out.File
	file_proto_consensus_consensus_proto_goTypes = nil
	file_proto_consensus_consensus_proto_depIdxs = nil
}