// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/consensus/consensus.proto

package cspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsensusService_RequestRunwayAssignment_FullMethodName = "/consensus.ConsensusService/RequestRunwayAssignment"
)

// ConsensusServiceClient is the client API for ConsensusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsensusServiceClient interface {
	RequestRunwayAssignment(ctx context.Context, in *RunwayRequest, opts ...grpc.CallOption) (*RunwayResponse, error)
}

type consensusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsensusServiceClient(cc grpc.ClientConnInterface) ConsensusServiceClient {
	return &consensusServiceClient{cc}
}

func (c *consensusServiceClient) RequestRunwayAssignment(ctx context.Context, in *RunwayRequest, opts ...grpc.CallOption) (*RunwayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunwayResponse)
	err := c.cc.Invoke(ctx, ConsensusService_RequestRunwayAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsensusServiceServer is the server API for ConsensusService service.
// All implementations must embed UnimplementedConsensusServiceServer
// for forward compatibility.
type ConsensusServiceServer interface {
	RequestRunwayAssignment(context.Context, *RunwayRequest) (*RunwayResponse, error)
	mustEmbedUnimplementedConsensusServiceServer()
}

// UnimplementedConsensusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsensusServiceServer struct{}

func (UnimplementedConsensusServiceServer) RequestRunwayAssignment(context.Context, *RunwayRequest) (*RunwayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestRunwayAssignment not implemented")
}
func (UnimplementedConsensusServiceServer) mustEmbedUnimplementedConsensusServiceServer() {}
func (UnimplementedConsensusServiceServer) testEmbeddedByValue()                          {}

// UnsafeConsensusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsensusServiceServer will
// result in compilation errors.
type UnsafeConsensusServiceServer interface {
	mustEmbedUnimplementedConsensusServiceServer()
}

func RegisterConsensusServiceServer(s grpc.ServiceRegistrar, srv ConsensusServiceServer) {
	// If the following call pancis, it indicates UnimplementedConsensusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsensusService_ServiceDesc, srv)
}

func _ConsensusService_RequestRunwayAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunwayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsensusServiceServer).RequestRunwayAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsensusService_RequestRunwayAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsensusServiceServer).RequestRunwayAssignment(ctx, req.(*RunwayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsensusService_ServiceDesc is the grpc.ServiceDesc for ConsensusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsensusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consensus.ConsensusService",
	HandlerType: (*ConsensusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestRunwayAssignment",
			Handler:    _ConsensusService_RequestRunwayAssignment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/consensus/consensus.proto",
}

const (
	InternalConsensusService_AppendEntry_FullMethodName = "/consensus.InternalConsensusService/AppendEntry"
	InternalConsensusService_RequestVote_FullMethodName = "/consensus.InternalConsensusService/RequestVote"
)

// InternalConsensusServiceClient is the client API for InternalConsensusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalConsensusServiceClient interface {
	AppendEntry(ctx context.Context, in *Decision, opts ...grpc.CallOption) (*DecisionAck, error)
	RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
}

type internalConsensusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalConsensusServiceClient(cc grpc.ClientConnInterface) InternalConsensusServiceClient {
	return &internalConsensusServiceClient{cc}
}

func (c *internalConsensusServiceClient) AppendEntry(ctx context.Context, in *Decision, opts ...grpc.CallOption) (*DecisionAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionAck)
	err := c.cc.Invoke(ctx, InternalConsensusService_AppendEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalConsensusServiceClient) RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, InternalConsensusService_RequestVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalConsensusServiceServer is the server API for InternalConsensusService service.
// All implementations must embed UnimplementedInternalConsensusServiceServer
// for forward compatibility.
type InternalConsensusServiceServer interface {
	AppendEntry(context.Context, *Decision) (*DecisionAck, error)
	RequestVote(context.Context, *VoteRequest) (*VoteResponse, error)
	mustEmbedUnimplementedInternalConsensusServiceServer()
}

// UnimplementedInternalConsensusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalConsensusServiceServer struct{}

func (UnimplementedInternalConsensusServiceServer) AppendEntry(context.Context, *Decision) (*DecisionAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntry not implemented")
}
func (UnimplementedInternalConsensusServiceServer) RequestVote(context.Context, *VoteRequest) (*VoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedInternalConsensusServiceServer) mustEmbedUnimplementedInternalConsensusServiceServer() {
}
func (UnimplementedInternalConsensusServiceServer) testEmbeddedByValue() {}

// UnsafeInternalConsensusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalConsensusServiceServer will
// result in compilation errors.
type UnsafeInternalConsensusServiceServer interface {
	mustEmbedUnimplementedInternalConsensusServiceServer()
}

func RegisterInternalConsensusServiceServer(s grpc.ServiceRegistrar, srv InternalConsensusServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalConsensusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalConsensusService_ServiceDesc, srv)
}

func _InternalConsensusService_AppendEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Decision)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalConsensusServiceServer).AppendEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalConsensusService_AppendEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalConsensusServiceServer).AppendEntry(ctx, req.(*Decision))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalConsensusService_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalConsensusServiceServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalConsensusService_RequestVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalConsensusServiceServer).RequestVote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalConsensusService_ServiceDesc is the grpc.ServiceDesc for InternalConsensusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalConsensusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consensus.InternalConsensusService",
	HandlerType: (*InternalConsensusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntry",
			Handler:    _InternalConsensusService_AppendEntry_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _InternalConsensusService_RequestVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/consensus/consensus.proto",
}