// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/common/common.proto

package cmpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFlightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	ClientVersion map[string]int32       `protobuf:"bytes,2,rep,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // para monotonic reads
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlightRequest) Reset() {
	*x = GetFlightRequest{}
	mi := &file_proto_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightRequest) ProtoMessage() {}

func (x *GetFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightRequest.ProtoReflect.Descriptor instead.
func (*GetFlightRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *GetFlightRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *GetFlightRequest) GetClientVersion() map[string]int32 {
	if x != nil {
		return x.ClientVersion
	}
	return nil
}

type FlightUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "A tiempo", "Retrasado", etc.
	Gate          string                 `protobuf:"bytes,3,opt,name=gate,proto3" json:"gate,omitempty"`
	VectorClock   map[string]int32       `protobuf:"bytes,4,rep,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Reloj vectorial
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightUpdate) Reset() {
	*x = FlightUpdate{}
	mi := &file_proto_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightUpdate) ProtoMessage() {}

func (x *FlightUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightUpdate.ProtoReflect.Descriptor instead.
func (*FlightUpdate) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *FlightUpdate) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *FlightUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FlightUpdate) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *FlightUpdate) GetVectorClock() map[string]int32 {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type FlightState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Gate          string                 `protobuf:"bytes,3,opt,name=gate,proto3" json:"gate,omitempty"`
	VectorClock   map[string]int32       `protobuf:"bytes,4,rep,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightState) Reset() {
	*x = FlightState{}
	mi := &file_proto_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightState) ProtoMessage() {}

func (x *FlightState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightState.ProtoReflect.Descriptor instead.
func (*FlightState) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *FlightState) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *FlightState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FlightState) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *FlightState) GetVectorClock() map[string]int32 {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type SeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	PassengerId   string                 `protobuf:"bytes,2,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatsRequest) Reset() {
	*x = SeatsRequest{}
	mi := &file_proto_common_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatsRequest) ProtoMessage() {}

func (x *SeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatsRequest.ProtoReflect.Descriptor instead.
func (*SeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *SeatsRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *SeatsRequest) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

type SeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatsMap      map[string]bool        `protobuf:"bytes,1,rep,name=seats_map,json=seatsMap,proto3" json:"seats_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Clave: string (ej. "21A", "05C") | Valor: false = no disponible, true = disponible
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatsResponse) Reset() {
	*x = SeatsResponse{}
	mi := &file_proto_common_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatsResponse) ProtoMessage() {}

func (x *SeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatsResponse.ProtoReflect.Descriptor instead.
func (*SeatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{4}
}

func (x *SeatsResponse) GetSeatsMap() map[string]bool {
	if x != nil {
		return x.SeatsMap
	}
	return nil
}

type CheckInRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Seat             string                 `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	FlightId         string                 `protobuf:"bytes,2,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	TargetDatanodeId string                 `protobuf:"bytes,3,opt,name=target_datanode_id,json=targetDatanodeId,proto3" json:"target_datanode_id,omitempty"`
	PassengerId      string                 `protobuf:"bytes,4,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_proto_common_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{5}
}

func (x *CheckInRequest) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *CheckInRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *CheckInRequest) GetTargetDatanodeId() string {
	if x != nil {
		return x.TargetDatanodeId
	}
	return ""
}

func (x *CheckInRequest) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

type CheckInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInResponse) Reset() {
	*x = CheckInResponse{}
	mi := &file_proto_common_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponse) ProtoMessage() {}

func (x *CheckInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponse.ProtoReflect.Descriptor instead.
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{6}
}

func (x *CheckInResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BoardingPassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassengerId   string                 `protobuf:"bytes,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	FlightId      string                 `protobuf:"bytes,2,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardingPassRequest) Reset() {
	*x = BoardingPassRequest{}
	mi := &file_proto_common_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardingPassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardingPassRequest) ProtoMessage() {}

func (x *BoardingPassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardingPassRequest.ProtoReflect.Descriptor instead.
func (*BoardingPassRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{7}
}

func (x *BoardingPassRequest) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

func (x *BoardingPassRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

type BoardingPassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Seat          string                 `protobuf:"bytes,2,opt,name=seat,proto3" json:"seat,omitempty"`
	Gate          string                 `protobuf:"bytes,3,opt,name=gate,proto3" json:"gate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardingPassResponse) Reset() {
	*x = BoardingPassResponse{}
	mi := &file_proto_common_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardingPassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardingPassResponse) ProtoMessage() {}

func (x *BoardingPassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardingPassResponse.ProtoReflect.Descriptor instead.
func (*BoardingPassResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{8}
}

func (x *BoardingPassResponse) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *BoardingPassResponse) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *BoardingPassResponse) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_common_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{9}
}

var File_proto_common_common_proto protoreflect.FileDescriptor

const file_proto_common_common_proto_rawDesc = "" +
	"\n" +
	"\x19proto/common/common.proto\x12\x06common\"\xc5\x01\n" +
	"\x10GetFlightRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12R\n" +
	"\x0eclient_version\x18\x02 \x03(\v2+.common.GetFlightRequest.ClientVersionEntryR\rclientVersion\x1a@\n" +
	"\x12ClientVersionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xe1\x01\n" +
	"\fFlightUpdate\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04gate\x18\x03 \x01(\tR\x04gate\x12H\n" +
	"\fvector_clock\x18\x04 \x03(\v2%.common.FlightUpdate.VectorClockEntryR\vvectorClock\x1a>\n" +
	"\x10VectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xdf\x01\n" +
	"\vFlightState\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04gate\x18\x03 \x01(\tR\x04gate\x12G\n" +
	"\fvector_clock\x18\x04 \x03(\v2$.common.FlightState.VectorClockEntryR\vvectorClock\x1a>\n" +
	"\x10VectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"N\n" +
	"\fSeatsRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12!\n" +
	"\fpassenger_id\x18\x02 \x01(\tR\vpassengerId\"\x8e\x01\n" +
	"\rSeatsResponse\x12@\n" +
	"\tseats_map\x18\x01 \x03(\v2#.common.SeatsResponse.SeatsMapEntryR\bseatsMap\x1a;\n" +
	"\rSeatsMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x92\x01\n" +
	"\x0eCheckInRequest\x12\x12\n" +
	"\x04seat\x18\x01 \x01(\tR\x04seat\x12\x1b\n" +
	"\tflight_id\x18\x02 \x01(\tR\bflightId\x12,\n" +
	"\x12target_datanode_id\x18\x03 \x01(\tR\x10targetDatanodeId\x12!\n" +
	"\fpassenger_id\x18\x04 \x01(\tR\vpassengerId\"+\n" +
	"\x0fCheckInResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"U\n" +
	"\x13BoardingPassRequest\x12!\n" +
	"\fpassenger_id\x18\x01 \x01(\tR\vpassengerId\x12\x1b\n" +
	"\tflight_id\x18\x02 \x01(\tR\bflightId\"[\n" +
	"\x14BoardingPassResponse\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x12\n" +
	"\x04seat\x18\x02 \x01(\tR\x04seat\x12\x12\n" +
	"\x04gate\x18\x03 \x01(\tR\x04gate\"\a\n" +
	"\x05EmptyB\x1eZ\x1clab_3/proto/common/cmpb;cmpbb\x06proto3"

var (
	file_proto_common_common_proto_rawDescOnce sync.Once
	file_proto_common_common_proto_rawDescData []byte
)

func file_proto_common_common_proto_rawDescGZIP() []byte {
	file_proto_common_common_proto_rawDescOnce.Do(func() {
		file_proto_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_common_proto_rawDesc), len(file_proto_common_common_proto_rawDesc)))
	})
	return file_proto_common_common_proto_rawDescData
}

var file_proto_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_common_common_proto_goTypes = []any{
	(*GetFlightRequest)(nil),     // 0: common.GetFlightRequest
	(*FlightUpdate)(nil),         // 1: common.FlightUpdate
	(*FlightState)(nil),          // 2: common.FlightState
	(*SeatsRequest)(nil),         // 3: common.SeatsRequest
	(*SeatsResponse)(nil),        // 4: common.SeatsResponse
	(*CheckInRequest)(nil),       // 5: common.CheckInRequest
	(*CheckInResponse)(nil),      // 6: common.CheckInResponse
	(*BoardingPassRequest)(nil),  // 7: common.BoardingPassRequest
	(*BoardingPassResponse)(nil), // 8: common.BoardingPassResponse
	(*Empty)(nil),                // 9: common.Empty
	nil,                          // 10: common.GetFlightRequest.ClientVersionEntry
	nil,                          // 11: common.FlightUpdate.VectorClockEntry
	nil,                          // 12: common.FlightState.VectorClockEntry
	nil,                          // 13: common.SeatsResponse.SeatsMapEntry
}
var file_proto_common_common_proto_depIdxs = []int32{
	10, // 0: common.GetFlightRequest.client_version:type_name -> common.GetFlightRequest.ClientVersionEntry
	11, // 1: common.FlightUpdate.vector_clock:type_name -> common.FlightUpdate.VectorClockEntry
	12, // 2: common.FlightState.vector_clock:type_name -> common.FlightState.VectorClockEntry
	13, // 3: common.SeatsResponse.seats_map:type_name -> common.SeatsResponse.SeatsMapEntry
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_common_common_proto_init() }
func file_proto_common_common_proto_init() {
	if File_proto_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_common_proto_rawDesc), len(file_proto_common_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_common_proto_goTypes,
		DependencyIndexes: file_proto_common_common_proto_depIdxs,
		MessageInfos:      file_proto_common_common_proto_msgTypes,
	}.Build()
	File_proto_common_common_proto = out.File
	file_proto_common_common_proto_goTypes = nil
	file_proto_common_common_proto_depIdxs = nil
}