// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/broker/broker.proto

package bpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	cmpb "lab_3/proto/common/cmpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatanodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatanodeId    string                 `protobuf:"bytes,1,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatanodeResponse) Reset() {
	*x = DatanodeResponse{}
	mi := &file_proto_broker_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatanodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatanodeResponse) ProtoMessage() {}

func (x *DatanodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatanodeResponse.ProtoReflect.Descriptor instead.
func (*DatanodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_broker_proto_rawDescGZIP(), []int{0}
}

func (x *DatanodeResponse) GetDatanodeId() string {
	if x != nil {
		return x.DatanodeId
	}
	return ""
}

var File_proto_broker_broker_proto protoreflect.FileDescriptor

const file_proto_broker_broker_proto_rawDesc = "" +
	"\n" +
	"\x19proto/broker/broker.proto\x12\x06broker\x1a\x19proto/common/common.proto\"3\n" +
	"\x10DatanodeResponse\x12\x1f\n" +
	"\vdatanode_id\x18\x01 \x01(\tR\n" +
	"datanodeId2\xc8\x02\n" +
	"\rBrokerService\x12<\n" +
	"\vQueryFlight\x12\x18.common.GetFlightRequest\x1a\x13.common.FlightState\x126\n" +
	"\vGetDatanode\x12\r.common.Empty\x1a\x18.broker.DatanodeResponse\x127\n" +
	"\bGetSeats\x12\x14.common.SeatsRequest\x1a\x15.common.SeatsResponse\x12:\n" +
	"\aCheckIn\x12\x16.common.CheckInRequest\x1a\x17.common.CheckInResponse\x12L\n" +
	"\x0fGetBoardingPass\x12\x1b.common.BoardingPassRequest\x1a\x1c.common.BoardingPassResponseB\x1cZ\x1alab_3/proto/broker/bpb;bpbb\x06proto3"

var (
	file_proto_broker_broker_proto_rawDescOnce sync.Once
	file_proto_broker_broker_proto_rawDescData []byte
)

func file_proto_broker_broker_proto_rawDescGZIP() []byte {
	file_proto_broker_broker_proto_rawDescOnce.Do(func() {
		file_proto_broker_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_broker_broker_proto_rawDesc), len(file_proto_broker_broker_proto_rawDesc)))
	})
	return file_proto_broker_broker_proto_rawDescData
}

var file_proto_broker_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_broker_broker_proto_goTypes = []any{
	(*DatanodeResponse)(nil),          // 0: broker.DatanodeResponse
	(*cmpb.GetFlightRequest)(nil),     // 1: common.GetFlightRequest
	(*cmpb.Empty)(nil),                // 2: common.Empty
	(*cmpb.SeatsRequest)(nil),         // 3: common.SeatsRequest
	(*cmpb.CheckInRequest)(nil),       // 4: common.CheckInRequest
	(*cmpb.BoardingPassRequest)(nil),  // 5: common.BoardingPassRequest
	(*cmpb.FlightState)(nil),          // 6: common.FlightState
	(*cmpb.SeatsResponse)(nil),        // 7: common.SeatsResponse
	(*cmpb.CheckInResponse)(nil),      // 8: common.CheckInResponse
	(*cmpb.BoardingPassResponse)(nil), // 9: common.BoardingPassResponse
}
var file_proto_broker_broker_proto_depIdxs = []int32{
	1, // 0: broker.BrokerService.QueryFlight:input_type -> common.GetFlightRequest
	2, // 1: broker.BrokerService.GetDatanode:input_type -> common.Empty
	3, // 2: broker.BrokerService.GetSeats:input_type -> common.SeatsRequest
	4, // 3: broker.BrokerService.CheckIn:input_type -> common.CheckInRequest
	5, // 4: broker.BrokerService.GetBoardingPass:input_type -> common.BoardingPassRequest
	6, // 5: broker.BrokerService.QueryFlight:output_type -> common.FlightState
	0, // 6: broker.BrokerService.GetDatanode:output_type -> broker.DatanodeResponse
	7, // 7: broker.BrokerService.GetSeats:output_type -> common.SeatsResponse
	8, // 8: broker.BrokerService.CheckIn:output_type -> common.CheckInResponse
	9, // 9: broker.BrokerService.GetBoardingPass:output_type -> common.BoardingPassResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_broker_broker_proto_init() }
func file_proto_broker_broker_proto_init() {
	if File_proto_broker_broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_broker_broker_proto_rawDesc), len(file_proto_broker_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_broker_broker_proto_goTypes,
		DependencyIndexes: file_proto_broker_broker_proto_depIdxs,
		MessageInfos:      file_proto_broker_broker_proto_msgTypes,
	}.Build()
	File_proto_broker_broker_proto = out.File
	file_proto_broker_broker_proto_goTypes = nil
	file_proto_broker_broker_proto_depIdxs = nil
}
