// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/broker/broker.proto

package bpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	cmpb "lab_3/proto/common/cmpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrokerService_QueryFlight_FullMethodName     = "/broker.BrokerService/QueryFlight"
	BrokerService_GetDatanode_FullMethodName     = "/broker.BrokerService/GetDatanode"
	BrokerService_GetSeats_FullMethodName        = "/broker.BrokerService/GetSeats"
	BrokerService_CheckIn_FullMethodName         = "/broker.BrokerService/CheckIn"
	BrokerService_GetBoardingPass_FullMethodName = "/broker.BrokerService/GetBoardingPass"
)

// BrokerServiceClient is the client API for BrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerServiceClient interface {
	QueryFlight(ctx context.Context, in *cmpb.GetFlightRequest, opts ...grpc.CallOption) (*cmpb.FlightState, error)
	GetDatanode(ctx context.Context, in *cmpb.Empty, opts ...grpc.CallOption) (*DatanodeResponse, error)
	GetSeats(ctx context.Context, in *cmpb.SeatsRequest, opts ...grpc.CallOption) (*cmpb.SeatsResponse, error)
	CheckIn(ctx context.Context, in *cmpb.CheckInRequest, opts ...grpc.CallOption) (*cmpb.CheckInResponse, error)
	GetBoardingPass(ctx context.Context, in *cmpb.BoardingPassRequest, opts ...grpc.CallOption) (*cmpb.BoardingPassResponse, error)
}

type brokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerServiceClient(cc grpc.ClientConnInterface) BrokerServiceClient {
	return &brokerServiceClient{cc}
}

func (c *brokerServiceClient) QueryFlight(ctx context.Context, in *cmpb.GetFlightRequest, opts ...grpc.CallOption) (*cmpb.FlightState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cmpb.FlightState)
	err := c.cc.Invoke(ctx, BrokerService_QueryFlight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) GetDatanode(ctx context.Context, in *cmpb.Empty, opts ...grpc.CallOption) (*DatanodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatanodeResponse)
	err := c.cc.Invoke(ctx, BrokerService_GetDatanode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) GetSeats(ctx context.Context, in *cmpb.SeatsRequest, opts ...grpc.CallOption) (*cmpb.SeatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cmpb.SeatsResponse)
	err := c.cc.Invoke(ctx, BrokerService_GetSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) CheckIn(ctx context.Context, in *cmpb.CheckInRequest, opts ...grpc.CallOption) (*cmpb.CheckInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cmpb.CheckInResponse)
	err := c.cc.Invoke(ctx, BrokerService_CheckIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) GetBoardingPass(ctx context.Context, in *cmpb.BoardingPassRequest, opts ...grpc.CallOption) (*cmpb.BoardingPassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cmpb.BoardingPassResponse)
	err := c.cc.Invoke(ctx, BrokerService_GetBoardingPass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServiceServer is the server API for BrokerService service.
// All implementations must embed UnimplementedBrokerServiceServer
// for forward compatibility.
type BrokerServiceServer interface {
	QueryFlight(context.Context, *cmpb.GetFlightRequest) (*cmpb.FlightState, error)
	GetDatanode(context.Context, *cmpb.Empty) (*DatanodeResponse, error)
	GetSeats(context.Context, *cmpb.SeatsRequest) (*cmpb.SeatsResponse, error)
	CheckIn(context.Context, *cmpb.CheckInRequest) (*cmpb.CheckInResponse, error)
	GetBoardingPass(context.Context, *cmpb.BoardingPassRequest) (*cmpb.BoardingPassResponse, error)
	mustEmbedUnimplementedBrokerServiceServer()
}

// UnimplementedBrokerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrokerServiceServer struct{}

func (UnimplementedBrokerServiceServer) QueryFlight(context.Context, *cmpb.GetFlightRequest) (*cmpb.FlightState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFlight not implemented")
}
func (UnimplementedBrokerServiceServer) GetDatanode(context.Context, *cmpb.Empty) (*DatanodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatanode not implemented")
}
func (UnimplementedBrokerServiceServer) GetSeats(context.Context, *cmpb.SeatsRequest) (*cmpb.SeatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeats not implemented")
}
func (UnimplementedBrokerServiceServer) CheckIn(context.Context, *cmpb.CheckInRequest) (*cmpb.CheckInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIn not implemented")
}
func (UnimplementedBrokerServiceServer) GetBoardingPass(context.Context, *cmpb.BoardingPassRequest) (*cmpb.BoardingPassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBoardingPass not implemented")
}
func (UnimplementedBrokerServiceServer) mustEmbedUnimplementedBrokerServiceServer() {}
func (UnimplementedBrokerServiceServer) testEmbeddedByValue()                       {}

// UnsafeBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServiceServer will
// result in compilation errors.
type UnsafeBrokerServiceServer interface {
	mustEmbedUnimplementedBrokerServiceServer()
}

func RegisterBrokerServiceServer(s grpc.ServiceRegistrar, srv BrokerServiceServer) {
	// If the following call pancis, it indicates UnimplementedBrokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrokerService_ServiceDesc, srv)
}

func _BrokerService_QueryFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cmpb.GetFlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).QueryFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_QueryFlight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).QueryFlight(ctx, req.(*cmpb.GetFlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_GetDatanode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cmpb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).GetDatanode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_GetDatanode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).GetDatanode(ctx, req.(*cmpb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_GetSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cmpb.SeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).GetSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_GetSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).GetSeats(ctx, req.(*cmpb.SeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cmpb.CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_CheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).CheckIn(ctx, req.(*cmpb.CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_GetBoardingPass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cmpb.BoardingPassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).GetBoardingPass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_GetBoardingPass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).GetBoardingPass(ctx, req.(*cmpb.BoardingPassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerService_ServiceDesc is the grpc.ServiceDesc for BrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "broker.BrokerService",
	HandlerType: (*BrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryFlight",
			Handler:    _BrokerService_QueryFlight_Handler,
		},
		{
			MethodName: "GetDatanode",
			Handler:    _BrokerService_GetDatanode_Handler,
		},
		{
			MethodName: "GetSeats",
			Handler:    _BrokerService_GetSeats_Handler,
		},
		{
			MethodName: "CheckIn",
			Handler:    _BrokerService_CheckIn_Handler,
		},
		{
			MethodName: "GetBoardingPass",
			Handler:    _BrokerService_GetBoardingPass_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/broker/broker.proto",
}
